manifest: update to 1.22.2
It doesn't build locally, probably because it runs out of memory:

   Compiling deltachat v1.60.0 (/run/build/deltachat-core-rust)
Running `rustc --crate-name deltachat --edition=2018 src/lib.rs
--error-format=json --json=diagnostic-rendered-ansi --crate-type lib
--emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto --cfg
'feature="default"' --cfg 'feature="vendored"' -C
metadata=5fad6f92f0713992 -C extra-filename=-5fad6f92f0713992 --out-dir
/run/build/deltachat-core-rust/target/release/deps -L
dependency=/run/build/deltachat-core-rust/target/release/deps --extern
anyhow=/run/build/deltachat-core-rust/target/release/deps/libanyhow-a69bfd18794f01ef.rmeta
--extern
async_imap=/run/build/deltachat-core-rust/target/release/deps/libasync_imap-87b256a548ae01c7.rmeta
--extern
async_native_tls=/run/build/deltachat-core-rust/target/release/deps/libasync_native_tls-d63de3f643c37c9c.rmeta
--extern
async_smtp=/run/build/deltachat-core-rust/target/release/deps/libasync_smtp-00718ab4eb1dba40.rmeta
--extern
async_std=/run/build/deltachat-core-rust/target/release/deps/libasync_std-8c14c6b496f72f3e.rmeta
--extern
async_std_resolver=/run/build/deltachat-core-rust/target/release/deps/libasync_std_resolver-511d95d3240d06e4.rmeta
--extern
async_tar=/run/build/deltachat-core-rust/target/release/deps/libasync_tar-ec9d8014e5fbec50.rmeta
--extern
async_trait=/run/build/deltachat-core-rust/target/release/deps/libasync_trait-bef9c7a1ea10ff52.so
--extern
backtrace=/run/build/deltachat-core-rust/target/release/deps/libbacktrace-c302b5833a08cd7d.rmeta
--extern
base64=/run/build/deltachat-core-rust/target/release/deps/libbase64-6a1180754b7ce1fe.rmeta
--extern
bitflags=/run/build/deltachat-core-rust/target/release/deps/libbitflags-e5df10eac5af3b30.rmeta
--extern
byteorder=/run/build/deltachat-core-rust/target/release/deps/libbyteorder-63b35d2635f2f241.rmeta
--extern
chrono=/run/build/deltachat-core-rust/target/release/deps/libchrono-6d0e15694dcdccd5.rmeta
--extern
deltachat_derive=/run/build/deltachat-core-rust/target/release/deps/libdeltachat_derive-c5d2e4476e46d43c.so
--extern
email=/run/build/deltachat-core-rust/target/release/deps/libemail-0c523d9b680da840.rmeta
--extern
encoded_words=/run/build/deltachat-core-rust/target/release/deps/libencoded_words-e48e6cdb7dcf9bb5.rmeta
--extern
escaper=/run/build/deltachat-core-rust/target/release/deps/libescaper-d9ac4f44a222ecea.rmeta
--extern
fast_socks5=/run/build/deltachat-core-rust/target/release/deps/libfast_socks5-79d69101adaa85ba.rmeta
--extern
futures=/run/build/deltachat-core-rust/target/release/deps/libfutures-9b3a814fe60bac2e.rmeta
--extern
hex=/run/build/deltachat-core-rust/target/release/deps/libhex-4d9a931a1c7235bb.rmeta
--extern
humansize=/run/build/deltachat-core-rust/target/release/deps/libhumansize-38a64114503615b8.rmeta
--extern
image=/run/build/deltachat-core-rust/target/release/deps/libimage-9ac241dd9871eaa0.rmeta
--extern
indexmap=/run/build/deltachat-core-rust/target/release/deps/libindexmap-0957acd97117bc78.rmeta
--extern
itertools=/run/build/deltachat-core-rust/target/release/deps/libitertools-a8d0ec7c705c3832.rmeta
--extern
exif=/run/build/deltachat-core-rust/target/release/deps/libexif-f7c2bc7fefb60c99.rmeta
--extern
lettre_email=/run/build/deltachat-core-rust/target/release/deps/liblettre_email-83eb5549a3dac5fd.rmeta
--extern
libc=/run/build/deltachat-core-rust/target/release/deps/liblibc-eed17fe2d768a932.rmeta
--extern
mailparse=/run/build/deltachat-core-rust/target/release/deps/libmailparse-835c3d392e4d47f9.rmeta
--extern
native_tls=/run/build/deltachat-core-rust/target/release/deps/libnative_tls-af6db559359167a2.rmeta
--extern
num_derive=/run/build/deltachat-core-rust/target/release/deps/libnum_derive-c06efd3f80d0eed0.so
--extern
num_traits=/run/build/deltachat-core-rust/target/release/deps/libnum_traits-dc44e77fda5f2142.rmeta
--extern
num_cpus=/run/build/deltachat-core-rust/target/release/deps/libnum_cpus-e55810e48eb60935.rmeta
--extern
once_cell=/run/build/deltachat-core-rust/target/release/deps/libonce_cell-9cdc32984ccf6d29.rmeta
--extern
percent_encoding=/run/build/deltachat-core-rust/target/release/deps/libpercent_encoding-7e3ddbba4522ce8a.rmeta
--extern
pgp=/run/build/deltachat-core-rust/target/release/deps/libpgp-97b92272a2b4c7f6.rmeta
--extern
quick_xml=/run/build/deltachat-core-rust/target/release/deps/libquick_xml-8a6aa1bfa75c4c57.rmeta
--extern
r2d2=/run/build/deltachat-core-rust/target/release/deps/libr2d2-a7fcda0ee0dce84d.rmeta
--extern
r2d2_sqlite=/run/build/deltachat-core-rust/target/release/deps/libr2d2_sqlite-095ce0c7dc7a18c6.rmeta
--extern
rand=/run/build/deltachat-core-rust/target/release/deps/librand-d30b6dca71c248ff.rmeta
--extern
regex=/run/build/deltachat-core-rust/target/release/deps/libregex-bbcc103a18723913.rmeta
--extern
rusqlite=/run/build/deltachat-core-rust/target/release/deps/librusqlite-432f6d115d0a1820.rmeta
--extern
hsluv=/run/build/deltachat-core-rust/target/release/deps/libhsluv-e0de375c4105c230.rmeta
--extern
sanitize_filename=/run/build/deltachat-core-rust/target/release/deps/libsanitize_filename-652b25ccabd133cc.rmeta
--extern
serde=/run/build/deltachat-core-rust/target/release/deps/libserde-010034a5efcb367b.rmeta
--extern
serde_json=/run/build/deltachat-core-rust/target/release/deps/libserde_json-4c6a3934d3057974.rmeta
--extern
sha1=/run/build/deltachat-core-rust/target/release/deps/libsha1-fb0d61492d787de4.rmeta
--extern
sha2=/run/build/deltachat-core-rust/target/release/deps/libsha2-f37e88ca9848ec83.rmeta
--extern
smallvec=/run/build/deltachat-core-rust/target/release/deps/libsmallvec-ce5a3ebb4eb2daab.rmeta
--extern
stop_token=/run/build/deltachat-core-rust/target/release/deps/libstop_token-6c6eaf91e437a511.rmeta
--extern
strum=/run/build/deltachat-core-rust/target/release/deps/libstrum-81958dc88bcc4bc7.rmeta
--extern
strum_macros=/run/build/deltachat-core-rust/target/release/deps/libstrum_macros-26a043c1fc43ea26.so
--extern
surf=/run/build/deltachat-core-rust/target/release/deps/libsurf-ea23e8700e8ce154.rmeta
--extern
thiserror=/run/build/deltachat-core-rust/target/release/deps/libthiserror-4a608890a55cb406.rmeta
--extern
toml=/run/build/deltachat-core-rust/target/release/deps/libtoml-b9fd389457de5baa.rmeta
--extern
url=/run/build/deltachat-core-rust/target/release/deps/liburl-05a8a8d273fcd714.rmeta
--extern
uuid=/run/build/deltachat-core-rust/target/release/deps/libuuid-db2b16aefe9027c7.rmeta
-g -L
native=/run/build/deltachat-core-rust/target/release/build/openssl-sys-01b55339be06bbbe/out/openssl-build/install/lib
-L
native=/run/build/deltachat-core-rust/target/release/build/libsqlite3-sys-0e3170a62ab317d2/out`
Running `rustc --crate-name deltachat --edition=2018
deltachat-ffi/src/lib.rs --error-format=json
--json=diagnostic-rendered-ansi --crate-type cdylib --crate-type
staticlib --emit=dep-info,link -C opt-level=3 -C lto --cfg
'feature="default"' --cfg 'feature="vendored"' -C
metadata=66c71d9b53c00a21 --out-dir
/run/build/deltachat-core-rust/target/release/deps -L
dependency=/run/build/deltachat-core-rust/target/release/deps --extern
anyhow=/run/build/deltachat-core-rust/target/release/deps/libanyhow-a69bfd18794f01ef.rlib
--extern
async_std=/run/build/deltachat-core-rust/target/release/deps/libasync_std-8c14c6b496f72f3e.rlib
--extern
deltachat=/run/build/deltachat-core-rust/target/release/deps/libdeltachat-5fad6f92f0713992.rlib
--extern
human_panic=/run/build/deltachat-core-rust/target/release/deps/libhuman_panic-057318f1539ba01b.rlib
--extern
libc=/run/build/deltachat-core-rust/target/release/deps/liblibc-eed17fe2d768a932.rlib
--extern
num_traits=/run/build/deltachat-core-rust/target/release/deps/libnum_traits-dc44e77fda5f2142.rlib
--extern
rand=/run/build/deltachat-core-rust/target/release/deps/librand-d30b6dca71c248ff.rlib
--extern
serde_json=/run/build/deltachat-core-rust/target/release/deps/libserde_json-4c6a3934d3057974.rlib
--extern
thiserror=/run/build/deltachat-core-rust/target/release/deps/libthiserror-4a608890a55cb406.rlib
-g -L
native=/run/build/deltachat-core-rust/target/release/build/openssl-sys-01b55339be06bbbe/out/openssl-build/install/lib
-L
native=/run/build/deltachat-core-rust/target/release/build/libsqlite3-sys-0e3170a62ab317d2/out`
error: could not compile `deltachat_ffi`

as if it's running out of memory or so.