pc: deltachat seems to expect "deltachat" prefix
It complains:

gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory
'/run/build/delta/node_modules/deltachat-node/build'
  cc '-DNODE_GYP_MODULE_NAME=deltachat' '-DUSING_UV_SHARED=1'
'-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1'
'-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64'
'-DBUILDING_NODE_EXTENSION' -I/app/include/node -I/app/src
-I/app/deps/openssl/config -I/app/deps/openssl/openssl/include
-I/app/deps/uv/include -I/app/deps/zlib -I/app/deps/v8/include
-I../../napi-macros  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter
-m64 -std=gnu99 -O3 -fno-omit-frame-pointer  -MMD -MF
./Release/.deps/Release/obj.target/deltachat/src/module.o.d.raw   -c -o
Release/obj.target/deltachat/src/module.o ../src/module.c
../src/module.c:9:10: fatal error: deltachat/deltachat.h: No such file
or directory
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [deltachat.target.mk:106:
Release/obj.target/deltachat/src/module.o] Error 1