Revert "Updated to 1.4.3"
This reverts commit 7140075f5929c130b44b48bd528f3d008e5e2c07, reversing
changes made to 21b82ab1ca25323861cdea9c36efaa27e2afdc69.

This is due to the app not working as expected.
v1.4.2 also doesn't work:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './tsc-dist/main'
Require stack:
- /app/delta/resources/app.asar/index.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
...